/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eoe_hellondk_NativeMath */

#ifndef _Included_cn_eoe_hellondk_NativeMath
#define _Included_cn_eoe_hellondk_NativeMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_eoe_hellondk_NativeMath
 * Method:    max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_eoe_hellondk_NativeMath_max
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
