/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eoe_hellondk_Bridge */

#ifndef _Included_cn_eoe_hellondk_Bridge
#define _Included_cn_eoe_hellondk_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_eoe_hellondk_Bridge
 * Method:    getNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_eoe_hellondk_Bridge_getNum
  (JNIEnv *, jobject);

/*
 * Class:     cn_eoe_hellondk_Bridge
 * Method:    callC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_eoe_hellondk_Bridge_callC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
